on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker
        run: |
          cd backend
          docker-compose -f docker-compose.yml up --build -d
          
#      - name: Install
#        run: |
#          cd backend
#          npm install
#
#      - name: Build
#         run:  |
#          cd backend
#          npm run build

#      - name: Test
#        run:  |
#          cd backend
#          npm test
