on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          cd frontend
          npm install

      - name: Build
        run: |
          cd frontend
          npm run build

      - name: Test
        run:  |
          cd frontend
          npm test

      - name: Cypress Test
        run:  |
          cd frontend
          npm run cy:run -- --spec "cypress/integration/app.test.ts"
