on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          cd frontend
          npm install

      - name: Build
        run: |
          cd frontend
          npm run build

      - name: Test
        run:  |
          cd frontend
          npm test

      - name: Cypress Test
        run:  |
          cd frontend
          # npm run cy:run -- --spec "cypress/integration/app.test.ts"
          - name: Run blog test
          
      - name: Cypress Test
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          working-directory: frontend
          wait-on: 'http://localhost:3000'
          config: baseUrl=https://localhost:3000
